### ISSUE TITLE
Missing definitions for filtermanager

### ISSUE THREAD

**Issue by emilekberg** [pixijs/pixi-typescript#10]
While doing some filter/shader programming i noticed that the filtermanager was missing definitions.

**Comment by clark-stevenson** [comment]
Hey @doskallemaskin 

The docs for this are a little hairy, I did my best with the FilterManager but I have no way to test it right now.  I would appreciate any PR fixing any issues or improvements you may have. 

Thanks!

**Comment by emilekberg** [comment]
Thanks, i'll take a look at it and play around some, see if i run into some issues, though this seems to have what i was missing :) good job!
