### ISSUE TITLE
Mesh constructor uvs,vertices and indices types mismatch

### ISSUE THREAD

**Issue by lucap86** [pixijs/pixi-typescript#105]
Mesh constructor types mismatch

```
constructor(texture: Texture, vertices?: number[], uvs?: number[], indices?: number[], drawMode?: number);
```

vertices should be `Float32Array`
indices  should be `Uint16Array`
uvs should be `Float32Array`

**Comment by clark-stevenson** [comment]
Thanks mate. Sorry for the delay 👍
