### ISSUE TITLE
A Basic ES6 Module Question

### ISSUE THREAD

**Issue by clark-stevenson** [pixijs/pixi-typescript#115]
Please take a look at Andrews [awesomely clean file](https://raw.githubusercontent.com/pixijs/pixi.js/dev/src/prepare/BasePrepare.js).  (I am still so happy to see ES6)

At the top are two variables. 

```
const SharedTicker = core.ticker.shared;
const DEFAULT_UPLOADS_PER_FRAME = 4;
```

But they are outside of the Class which is the default export. 

From a TypeScript perspective, are these hidden from view?  I mean on the class, you have private/protected/public and really you need to add them all.  But, these consts, and other functions at the same level of the class, I am not sure if I just ignore them?

**Comment by englercj** [comment]
I dont see a reason to have anything in the typescript definitions that isn't exposed to the user (and these aren't)

**Comment by clark-stevenson** [comment]
Thanks for confirming! 👍
