### ISSUE TITLE
No external module?

### ISSUE THREAD

**Issue by drrcknlsn** [pixijs/pixi-typescript#12]
The `PIXI` module does not appear to be declared external, and when referencing it, I am unable to import it.  Also, the module name does not match the npm module name ("PIXI" vs. "pixi.js"), so after compiling the TypeScript, the compiled JavaScript references "PIXI", where npm references "pixi.js".  I have fixed this in my own code by changing the module to be external and use the same module name as npm:

```
declare module "pixi.js" {

    export function autoDetectRenderer(width: number, height: number, options?: RendererOptions, noWebGL?: boolean): WebGLRenderer | CanvasRenderer;
    export var loader: loaders.Loader;
```

And referenced in my code:

```
/// <reference path="../node_modules/pixi-typescript/pixi.d.ts" />
import PIXI = require('pixi.js');
```

I'm not terribly experienced with TypeScript yet, so if I have missed something, and this is the wrong solution, please let me know.  Thanks.

**Comment by englercj** [comment]
Good call, likely need to add something along these lines to this lib:

``` ts
declare module 'pixi.js' {
    var _pixi: PIXI;
    export = _pixi;
}
```

**Comment by clark-stevenson** [comment]
Hey @drrcknlsn thanks! 

Man I am on the cusp of what you are saying! I am at this time trying to get to grips with require+vs+typescript. I would love anyone else to chip in 2 cents because I will struggle with this myself.

**Comment by clark-stevenson** [comment]
Man we need to get @englercj a set of angel wings!

**Comment by clark-stevenson** [comment]
@drrcknlsn do you fancy trying adding @englercj 's sample to your existing setup (remove your own)? See if it behaves as expected? I do not want to change "PIXI" because if you do that, you break `non-require` usage. (leaving me with pixi.js.autoDetectRenderer).  I get no errors in the definition by pasting his code below the existing "PIXI" module but I am unable to test it.

**Comment by drrcknlsn** [comment]
Thank you for getting back to me.  I tried @englercj 's solution and got:

```
error TS2339: Property 'Container' does not exist on type 'PIXI'.
```

**Comment by drrcknlsn** [comment]
So, I played with the other solution a bit, and this seemed to do the trick:

```
declare module 'pixi.js' {
  export = PIXI;
}
```

**Comment by clark-stevenson** [comment]
I was looking for how to do that! Awesome! @englercj was correct but it had implementation, whereas we needed the declarative version of the same meaning which you provided. In a few weeks time, I would have faced your problem but not known it was the definition , you saved me so much time!
