### ISSUE TITLE
Test of full conversion with bunnies.

### ISSUE THREAD

**Issue by ivanpopelyshev** [pixijs/pixi-typescript#124]
Its here: https://github.com/pixijs/pixi-typescript/tree/secret-project

@clark-stevenson I need your expertise, I cant do that alone. 

We have to convert all the relevant parts to test it with "bunny" demo which will be provided by @GoodBoyDigital .

I already tried conversion to Kotlin, so it must look like https://github.com/pixijs/pixi-native as a result.

If our demo will be faster than current pixijs-v4 , then we can have full official conversion :)

In the future,  other plugins will be included in the same repo, and we just built different sets of "ts" files.

**Comment by staff0rd** [comment]
> If our demo will be faster than current pixijs-v4

What do you expect to be faster?

**Comment by ivanpopelyshev** [comment]
> What do you expect to be faster?

@GoodBoyDigital said we lost some FPS on moving to ES6 or may be static transforms. We need a better benchmark.

I really don't know, @englercj also said that our StaticTransform.updateTransform is not optimized, but failed to give us any method to analyze it. 

I understand that its all is a dancing with a tambourine.

**Comment by clark-stevenson** [comment]
I would like to help out if I can!

The only thing is, I don't fully see how anything could be faster from this end point since this TS declaration is just a dev tool.  I think that is why @staff0rd wondered what you expected to be faster.

**Comment by ivanpopelyshev** [comment]
> The only thing is, I don't fully see how anything could be faster from this end point since this TS declaration is just a dev tool.

The point is to get from @GoodBoyDigital the test where ES6 version is losing to ES5. I don't understand it too :)

**Comment by clark-stevenson** [comment]
Closing this as it is fairly stale and I don't think it is applicable.  If it is, reopen!
