### ISSUE TITLE
Add HTMLVideoElement type to BaseTexture.source

### ISSUE THREAD

**Issue by mmykola** [pixijs/pixi-typescript#126]
Hello,
I'm attempting to use a example VideoBaseTexture.baseTexture.source, but source hasn't type HTMLVideoElement for Video tag, it can be type HTMLImageElement | HTMLCanvasElement only.

Sorry for my English!
Thanks!

**Comment by clark-stevenson** [comment]
Thanks 👍  This should be resolved.
