### ISSUE TITLE
No MovieClip in extras

### ISSUE THREAD

**Issue by michaelsaprykin** [pixijs/pixi-typescript#127]

**Comment by sbimikesmullin** [comment]
@MikeSaprykin why did you close this? did you find it somewhere? its missing for us, too.

**Comment by ivanpopelyshev** [comment]
It was renamed to AnimationSprite or so.. gonna fix it

**Comment by michaelsaprykin** [comment]
@sbimikesmullin Yeah, I've closed that, because I digged a bit deeper and found it in AnimationSprite, so it was renamed.

**Comment by clark-stevenson** [comment]
Is the solution to this to make the depreciation list somewhere at the bottom of the file?

If so, how would one generally handle this?  Would you simply say:

`export class AbstractFilter extends core.Filter` ?

```
    AbstractFilter: {
        enumerable: true,
        get()
        {
            warn('AstractFilter has been renamed to Filter, please use PIXI.Filter');

            return core.Filter;
        },
    }
```
