### ISSUE TITLE
Getter and setter for Text.style

### ISSUE THREAD

**Issue by bluepichu** [pixijs/pixi-typescript#135]
There's a strange type issue in `Text`'s style property due to how its getter and setter work:

- When you set a `Text` object's `style` property, you may pass it a _partial_ `TextStyle` object (which this library calls `TextStyleOptions`), which is the same as a `TextStyle` except that all of its fields are optional.  Pixi will then expand this into a full `TextStyle` object as part of the setter.

- When you get a `Text` object's `style` property, it simply returns the `TextStyle` object.

Thus, a correct definition should look something like this:

```ts
class Text extends Sprite {
    // ...
    set style(sty: TextStyleOptions);
    get style(): TextStyle;
}
```

However, TS allows neither getter and setter declarations nor getters and setters with disagreeing types.

The current solution to this in pixi-typescript is that the `style` field is typed as `TextStyle`, which means that you need to work around it a bit to get an assignment to typecheck:

```ts
// Create text object
let text = new PIXI.Text("Hello world!", { fontFamily: "Arial", fontSize: "20px" });

// Problem: we'd like to do this, but it doesn't typecheck.
text.style = { fontFamily: "Roboto", fontSize: "24px" };

// Solution 1: call the TextStyle constructor before passing.
text.style = new PIXI.TextStyle({ fontFamily: "Roboto", fontSize: "24px" });

// Solution 2: add a type assertion.
text.style = { fontFamily: "Roboto", fontSize: "24px" } as PIXI.TextStyle;
```

This is annoying, but I'm not sure if typing it as `TextStyleOptions` would really be any better; it would be nicer for assignment, but potentially much worse when using the getter to operate upon it (since it's now missing the `styleId` field and its methods, and the remaining fields are all optional when they shouldn't be).  Unfortunately, after reading some of the getter- and setter-related issues on the TS repo, it sounds like allowing these to have different types is impossible as getters and setters are modeled in the typesystem as properties and not as methods.

Thoughts?

**Comment by clark-stevenson** [comment]
Sorry I took so long to get around to this. It really did hurt my head at first because I totally know what you mean, but I can't think of a solution other than your first solution which although kind of sucks, the next best solution is `any` as far as I can see, and that isn't ideal either but maybe it actually makes more sense!

I am also wondering how this could  be solved in the JavaScript implementation, but I don't really have a solution to propose to the core team.

**Comment by clark-stevenson** [comment]
Closing the issue as stale and I don't see a relevant solution other than what is available without implementation change.
