### ISSUE TITLE
Is resource-loader out dated?

### ISSUE THREAD

**Issue by brenwell** [pixijs/pixi-typescript#137]
Thanks for the lib!

I was having a quick browse through the source and in the comments it says

```
    // extends
    // https://github.com/englercj/resource-loader/
    // 1.6.4
```

Pixi 4.0.0's package.json has `"resource-loader": "^1.8.0"`
Pixi 4.3.2's package.json has `"resource-loader": "^2.0.3"`

Is it possible that the definitions for the PIXI.Loader is outdated, or is the comment simply old

Sorry if I wasted your time with a stupid question

**Comment by clark-stevenson** [comment]
It is not a stupid question at all 👍

Good point.  I know that the ResourceLoader was updated recently in a way that caused some problems, I will review the dependencies next time I commit.

**Comment by ivanpopelyshev** [comment]
Yes, and its a big problem, we have to change definitions for some things. Their definition of "add" is hell

**Comment by clark-stevenson** [comment]
They were outrageously out of date. Thanks for pointing it out @brenwell 

It should be sorted out now. I just wanted to take note to ensure Ivan wasn't stranded with spine, and that his `add` problems are resolved before I close.

**Comment by clark-stevenson** [comment]
But now I am doubtful....

The example that I modified, I knew it was missing an event listener which is the cb.  But as far as I can see, there is no `once` any more as the example insists. 

https://github.com/pixijs/examples/blob/gh-pages/required/examples/basics/custom-filter-v3.js#L33

Where does that come from?

**Comment by staff0rd** [comment]
resource-loader v2 switched to signals so now its `loader.onComplete.add(() => { .. })`.

**Comment by staff0rd** [comment]
Apologies; `loader.onComplete.once(() => { .. })`.

**Comment by ivanpopelyshev** [comment]
@staff0rd some people told me its still "on" and "once". So far updating resource-loader is controversal, no one made quality control on that.

**Comment by staff0rd** [comment]
@ivanpopelyshev they're still there but deprecated; https://github.com/pixijs/pixi.js/blob/0a9d248688852ba79d5e63d4ab5379630bd00511/src/loaders/loader.js#L48-L53

**Comment by ivanpopelyshev** [comment]
@staff0rd some people said that user doesnt have to know about signals at all, and I cant expose them through pixi.

**Comment by staff0rd** [comment]
@ivanpopelyshev you can use signals or events due to code I linked above.  Possibly signals are better to use if [pixi v5](https://github.com/pixijs/pixi.js/projects) is going to switch to them also.

**Comment by ivanpopelyshev** [comment]
There was huge discussion in slack regarding https://github.com/pixijs/pixi.js/pull/3570 

As a result I'm angry :)

**Comment by staff0rd** [comment]
Yeah I read the discussion in slack, but apart from the caching issues I don't understand what is your main concern with the resource loader.  I also don't understand why #3570 is required considering that dependency is specific to the resource loader, not pixi.

**Comment by clark-stevenson** [comment]
I still don't really see `on` or `once` anywhere in the ResourceLoader at all.  

Thanks for the link to v5, I really really need to check out `tsd-jsdoc` and try to understand it better.  I desperately want to get these types, without manual errors, into the official build.

**Comment by staff0rd** [comment]
@clark-stevenson EventEmitter is stuck on `Loader` via [pixi for compatibility](https://github.com/pixijs/pixi.js/commit/2b90d73b8bcf84fff491d1775ab1a768f63b55a1#diff-14b9d81e354c5e72b5a2c3f20fa6280dR40) - ResourceLoader itself no longer uses it due to switching to signals.

**Comment by clark-stevenson** [comment]
This should be resolved, I will be improving it further as I do the new v4 examples/tests.
