### ISSUE TITLE
HTMLElement || HTMLCanvasElement

### ISSUE THREAD

**Issue by lexfrost** [pixijs/pixi-typescript#139]
Hello

Should line 749 reference the 'view' as an HTMLElement rather than HTMLCanvasElement?

export interface IRendererOptions {
     view?: HTMLElement;

Thanks 

Lex

**Comment by ivanpopelyshev** [comment]
Because its always a Canvas renderer, there's no DOM renderer.

**Comment by clark-stevenson** [comment]
Yeah I would agree with Ivan. It has to be a `HTMLCanvasElement`. Always worth checking these things though so thanks 👍
