### ISSUE TITLE
Publish to http://definitelytyped.org

### ISSUE THREAD

**Issue by bfanger** [pixijs/pixi-typescript#14]
`tsd install pixi --save` installs outdated (v1.3) pixi definitions.

I'd love to see definitions for pixi 2.x and 3.x on http://definitelytyped.org/tsd/

My workaround for now is:

``` sh
git submodule add https://github.com/pixijs/pixi-typescript.git typings/pixi
tsd rebundle
```

**Comment by clark-stevenson** [comment]
Hey @bfanger 

Do you know what I would need to do to accomplish this?  

Cheers!

**Comment by bfanger** [comment]
I've found a contributing guide: http://definitelytyped.org/guides/contributing.html

[Here](https://github.com/borisyankov/DefinitelyTyped/tree/master/node) is example of a library with multiple versions.

If you want, I can make the pull request to [borisyankov/DefinitelyTyped](https://github.com/borisyankov/DefinitelyTyped) using the definitions from this repo.

**Comment by clark-stevenson** [comment]
Sorry for the long delay! Long weekend. 

It would be awesome if you could make a PR. 

Just one question, what happens to maintenance? Does it mean that there is going to be 2 versions of this d.ts file?  That there will be PRs happening over at DT (being merged by a random person unconnected to the project) and ones happening here?

Also see https://github.com/borisyankov/DefinitelyTyped/issues/3541

**Comment by emilekberg** [comment]
+1 on this, would make it a bit easier for me to work. I did publish one definition some time ago and it's pretty much adding a header and making a type-test file, making sure that the syntax is correct.

**Comment by clark-stevenson** [comment]
This has been done, thanks @bfanger for making it possible!  

From my next commit onwards, I will attempt to make PRs to DT as well as here.
