### ISSUE TITLE
Cannot assign to 'SCALE_MODE' because it is a constant or a read-only property.

### ISSUE THREAD

**Issue by nullstar** [pixijs/pixi-typescript#148]
There's currently an issue with settings properties in that you cannot assign to them, for example:

`PIXI.settings.SCALE_MODE = PIXI.SCALE_MODES.NEAREST;`

Doing so results in the following error:

> Cannot assign to 'SCALE_MODE' because it is a constant or a read-only property.

**Comment by clark-stevenson** [comment]
My bad! I did it when I was fixing TSLint.  Thanks guys 👍
