### ISSUE TITLE
TS2339 When accessing protected inherited property after checking if "this instanceof someClass"

### ISSUE THREAD

**Issue by intoxopox** [pixijs/pixi-typescript#151]
I'm getting "TS2339 TypeScript Property does not exist on type." when I try to access an inherited protected property in a conditional that checks if current class is an instance of some class in the inheritance chain. For example:
`if (this instanceof SomeChildClass) {
	this.someBaseClassProtectedProp = someNewValue;
}`
This results in the following error:
Error TS2339	Property 'someBaseClassProtectedProp' does not exist on type 'this & SomeChildClass'

This only happens if the property is protected instead of public. For now, I can prevent this error by rolling back to definitions for Pixi.js 4.3.4.

**Comment by clark-stevenson** [comment]
Thanks @intoxopox 

I am not 100% sure how to reproduce, but is the problem resolved if you cast?  `this` is a strange one to me. Had it been anything but `this`. as in

```
if (something instanceof Animal){
     let myAnimal = something as Animal;
     myAnimal.derp = 3000;  
}
```

Does casting like this resolve the issue?

```
if (this instanceof SomeChildClass) { 
    (<SomeChildClass>this).someBaseClassProtectedProp = someNewValue; 
}
```

**Comment by ivanpopelyshev** [comment]
Yep, no smart cases for typescript, that's a Kotlin feature :)

**Comment by intoxopox** [comment]
Yes, casting resolves it, though not sure why this would be needed now, but not so a few releases ago. That casting should be automatically inferred in current typescript. At any rate, casting is a suitable workaround. Was just hoping someone could provide some clues as to what changed, making this happen suddenly. I suppose chalk another one up to the schizophrenia of 'this'.

**Comment by ivanpopelyshev** [comment]
Did you change variable type in that place?

**Comment by intoxopox** [comment]
Hi Ivan. Not sure what you mean.

**Comment by clark-stevenson** [comment]
Do you know what it is that you feel isn't being inferred? There was a lot of changed for a while. Be interesting to see if your problem can be fixed, especially if going back solves it.  (A particular class / property).

**Comment by intoxopox** [comment]
Using the d.ts for 4.3.4, hovering over 'this' when used inside "if (this instanceof SomeChildClass)" block shows "this: SomeChildClass". However, using d.ts for 4.4.0, hovering over 'this' shows "this & SomeChildClass". So in d.ts 4.3.4, the type for 'this' is correctly inferred to be of type SomeChildClass... because it's being evaluated inside the block "if (this instanceof SomeChildClass)". In 4.4.0, the type is mangled to some strange hybrid or mixin or something. Whatever "this & SomeChildClass" is supposed to mean. It can still see inherited properties/methods that are public, but no longer ones that are protected... presumably because whatever "this & SomeChildClass" is as a type, isn't considered to be part of the valid inheritance chain any longer.
A bit confusing to try to explain, but hope that makes sense.

**Comment by clark-stevenson** [comment]
What does `SomeChildClass` extend?  I don't really know how to reproduce and by looking at the code between these 2 versions, I don't know where the problem lies.  (For example, is `SomeChildClass` a `DisplayObject`?). 

I have some updates to do later, and was hoping to update DT, but the mangled type is concerning me.

**Comment by intoxopox** [comment]
In my example, 'this' is an instance extending PIXI.Container. We'll call it SomeBaseClass... and SomeChildClass extends SomeBaseClass. Just holler if you'd like me to put together a small example app.

**Comment by clark-stevenson** [comment]
I was trying something like this but got no strange results so far. 

```
class SomeBaseClass extends PIXI.Container {

    protected iAmProtected: boolean = true;

}

class SomeChildClass extends SomeBaseClass {

    constructor() {
  
        super();
       
        if (this instanceof SomeChildClass) {

            // protected from container
            this._calculateBounds();

            // protected from SomeBaseClass
            this.iAmProtected = false;

        }

    }

    allTheThings(stuff: any){

        if (this instanceof SomeChildClass){
            this._calculateBounds();
            this.iAmProtected = true;
        }

    }

}
```

**Comment by ivanpopelyshev** [comment]
constrctor

**Comment by clark-stevenson** [comment]
Good call! Bad copy paste, but it is still passing without error.

**Comment by intoxopox** [comment]
Instead of having "if (this instanceof SomeChildClass) {" in SomeChildClass, put that same statement in SomeBaseClass. That's the sort of thing that's causing errors for me.

**Comment by clark-stevenson** [comment]
This one has defeated me for 4-5 hours over the last couple of days. 

My only solution is casting to work around the issue at this time.

```
if (this instanceof Thing){
    
} 
```

Inside that block,  I believe `this` becomes a `Union Intersection`.  It has the types of `this & Thing`.  Now the TypeScript compiler appears to be confused.  I can't eloquently describe the problem well enough to search for it,  but even within this is why `this & Thing` can't access protected methods.  I have no idea why it used to work, but now doesn't

**Comment by intoxopox** [comment]
Ah... that explanation does seem to fit.

**Comment by clark-stevenson** [comment]
Oh well this will probably never be fixed at least on V4 and casting will need to do the job.
