### ISSUE TITLE
Typings for event handlers

### ISSUE THREAD

**Issue by asheb** [pixijs/pixi-typescript#152]
Just curious why they've been [commented out](https://github.com/pixijs/pixi-typescript/blob/v4.x/pixi.js.d.ts#L391-L425).

**Comment by clark-stevenson** [comment]
Hey @asheb 

Pure Lazyness!  Thanks for reminding me. 

I spent some time last night fixing it so it will be in the next commit. 

![untitled](https://cloud.githubusercontent.com/assets/4239553/24299088/e4965f32-109f-11e7-9161-92966a3bb164.png)

**Comment by asheb** [comment]
Cool! Thanks a lot!
