### ISSUE TITLE
Fix Test point.clone() fails.

### ISSUE THREAD

**Issue by clark-stevenson** [pixijs/pixi-typescript#156]
[This](https://github.com/pixijs/pixi-typescript/blob/v4.x/pixi.js-tests.ts#L1705) line is broken on tests and is related to this [PR](https://github.com/pixijs/pixi-typescript/commit/1c6ba2471cf9bcec629077a958452c161ff037fd)

**Comment by ivanpopelyshev** [comment]
yeah, i forgot that :) Observable doesnt have a clone, we have to create point and then copy it.

**Comment by clark-stevenson** [comment]
Is there any way to make the 2 types interchangable? Can `ObservablePoint` gain a `clone()` method?

Otherwise it seems these properties are either `Points` or `ObservablePoints` but not both as incompatible.

**Comment by ivanpopelyshev** [comment]
I tried. @englercj rejected it. Just get rid of clone() method.

**Comment by clark-stevenson** [comment]
Get rid of the `clone()` method from `Point` ?

**Comment by clark-stevenson** [comment]
So I think I am going to go ahead with removing `clone()` from point shortly unless there is any objections from anyone.

**Comment by francisvidal** [comment]
So you decide that even if PIXI support cloning a Point we won't be able to do it in TS?

**Comment by ivanpopelyshev** [comment]
i think its better to leave clone() as it is. Let it fail. )

**Comment by clark-stevenson** [comment]
i will add it back tomorrow and remove it from the tests but I still don't really like it.  Not sure why `ObservablePoint.clone()` was rejected.

**Comment by ivanpopelyshev** [comment]
Because I think it has to return Point, while @englercj thinks it has to be Observable with the same callback, so we have a collision there ;)

**Comment by englercj** [comment]
If we are going to call people out, let's at least give the context. I gave multiple options for how it could work, and you decided instead to take it out of your PR:

https://github.com/pixijs/pixi.js/pull/2678#issuecomment-229850250

**Comment by ivanpopelyshev** [comment]
Thank you for providing the context ;) My argument was that clone() is often called from properties that are points from the perspective of DisplayObject interface, and user wants Point. 

The real solution is to merge two point classes in one to avoid all that strange inheritance, I think we can agree on that. Its shame that JS doesnt have built-in mechanisms for copy-by-value.

**Comment by jmlee2k** [comment]
Some function definitions will need to be updated in order for this to work.  For example, take DisplayObject::toGlobal, which is defined as:

`        toGlobal(position: Point, point?: Point, skipUpdate?: boolean): Point;`

This won't compile when passing a DisplayObject.position as the position, as it's defined as follows:

`        position: Point | ObservablePoint;`

Therefore, you'll get an error that type `Point | ObservablePoint` is not assignable to parameter of type 'Point' (due to the missing clone() method).

I've only been working with Pixi for a short time, so I'm not too familiar with it's inner workings yet, but I think this could be fixed (at least in simple cases like this) by declaring a new interface:

`interface PointLike{x:number,y:number}`

Both `Point `and `ObservablePoint `could than implement this interface, and then `PointLike `could be used as the parameter type in DisplayObject::toGlobal, and any other functions which only expect an object with x and y properties.

I'm not sure if that's the right way to go, or if the proper solution is just to change the declaration of DisplayObject.toGlobal to accept `Point | ObservablePoint`.  In that case, I suggest declaring a PointLike type as follows:

`type PointLike = Point | ObservablePoint`

This could then be used in all the places where `Point | ObservablePoint` is used today.  I'm happy to submit either change as a PR once someone with a bit more knowledge of how Pixi works can give their input.

Thoughts?

**Comment by ivanpopelyshev** [comment]
I think its best to extend ObservablePoint with Point interface in TS? Even if its not extended in pixi

**Comment by jmlee2k** [comment]
Ok, how about this?

PointLike can now be used / returned anywhere in the d.ts file, and it suggests a relationship between Point and ObservablePoint while making it clear that equals and clone are not part of ObservablePoint.

```
    class PointLike
    {
        x: number;
        y: number;

        set(x?: number, y?: number): void;
        copy(point: PointLike): void;        
    }

    export class ObservablePoint extends PointLike
    {
        constructor(cb: () => any, scope?: any, x?: number, y?: number);
        cb: () => any;
        scope: any;
    }

    export class Point extends PointLike
    {
        constructor(x?: number, y?: number);
        clone(): Point;
        equals(p: PointLike): boolean;
    }
```

**Comment by ivanpopelyshev** [comment]
Yeah, something like that will work. But its too many changes for existing projects :( However I know that I'm biased in this topic, so let @clark-stevenson decide :)

**Comment by jmlee2k** [comment]
Sounds good.  I don't think there would be many (if any) changes to existing projects, since I'm just talking about the d.ts file at this point.  Obviously changing the actual pixi js code would be a much bigger deal.

**Comment by clark-stevenson** [comment]
@jmlee2k 

I appreciate you taking time to look at this.  I would happily accept a PR if you are comfortable to do so. 👍

**Comment by ivanpopelyshev** [comment]
Actually, I support PointLike too. I'm writing new typescript renderer based on pixijs, and I have that interface :)

**Comment by jmlee2k** [comment]
@clark-stevenson 

Sure, I'm happy to put together a PR, and we can discuss further.

**Comment by clark-stevenson** [comment]
Sounds interesting Ivan 💃  Never bad to see more TypeScript usage! 

There is one thing that bothers me still though.  If you look at the above PR at the very top of this issue, you see:

`position: Point | ObservablePoint`

If that becomes 

`position: PointLike`

How do you then know whether you are looking at a `Point` or an `ObservablePoint`?   Unlike the first line, you don't actually know unless you go looking for what `PointLike` means. 

Eek I forgot TS Syntax for casting but basically you need to `(<Point>thing.position).clone()`?

**Comment by jmlee2k** [comment]
@clark-stevenson 

True, it's not as easy to figure out whats going on with that syntax.  I've looked at it a bunch more, and I think I have a solution which will address my specific problem, while also giving us the `PointLike` type which we can use to describe things if and when it's necessary.

For example, if we follow the chain of `Sprite::containsPoint`, we can see that it is only using the x and y properties of the point param, so we could change the param type to `PointLike `to better communicate that.

I'll work on a small PR, and we can discuss more there.

On another note, what was the actual problem that triggered this?  I tried to follow the link at the top of the issue, but it seems to link to a blank line.

**Comment by jmlee2k** [comment]
Ok, I've created a pull request.  It doesn't (and can't) solve the underlying issue, but it restores the ability to pass Point|ObserveablePoint objects to DisplayObject::toLocal and DisplayObject::toGlobal, as well as adding an easy way to describe the same pattern elsewhere.

In addition, I think it better clarifies the relationship between Point and ObservablePoint.

#163

**Comment by clark-stevenson** [comment]
I think I posted in the wrong Issue before! 

Thanks @jmlee2k I was able to past the test with some casting and I made a PR to DT so it should be all up to date everywhere shortly.
