### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by tbillington** [pixijs/pixi-typescript#164]
Feels like a silly question but how do I use this? I check npm and typings but I can't seem to find this repo on either of them... Do I just copy the .d.ts file into my project manually? Really confused.

Thanks

**Comment by tbillington** [comment]
I ended up installing the alternative suggested in the readme and it worked. ¯\\_(ツ)_/¯

**Comment by clark-stevenson** [comment]
I need to update that DefinitlyTyped as it is fairly outdated. Will make a PR in the next couple of days thanks for reminding me 👍

**Comment by tbillington** [comment]
No worries. I'm fumbling my way around typescript so I don't know what the usual practise is :) 

Can close this if you like.

**Comment by clark-stevenson** [comment]
I made a PR at DT to bring it up to date with today. 

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17099

It should be merged in a few days or so and yeah `npm install @types/pixi.js` is the "normal" method (but I don't use it so not the best to give advice). 

Cheers! 👍

**Comment by bermick** [comment]
so what would be the correct way to use it @clark-stevenson? in the README you're specifying that doing `npm install @types/pixi.js` can be outofdate
thanks!

**Comment by clark-stevenson** [comment]
@bermick 

Yeah I would use `npm install @types/pixi.js` these days.

The confusion stems from the fact that at the time, pixi dev was rapid, and there was a lot of commit history to troll through.  DT can be tedious when updating so much.

Anyway that is no longer a problem as the API has stabilised, especially in 2018.  There are very few updates that we care about in TypeScript even though the V4 continues to be developed. 

So yeah `npm install @types/pixi.js` will always match the latest stable release by the core team (give or take a few days).  This repo is just really a dev update which I do every couple of weeks and is no longer a concern for anyone really. 

I will update this readme to be clear so thanks for pointing this out 👍
