### ISSUE TITLE
Greater Parity with DT

### ISSUE THREAD

**Issue by clark-stevenson** [pixijs/pixi-typescript#165]
Basically this repo has to adapt so that there is some kind of resemblance with DT.  

1. `pixi.d.ts` must become `index.d.ts`
1. All of the changes I have to make for DT (to pass all the tests) is a whole separate thing.  So I spend about an hour changing this file, into a DT acceptable one, and now, I have a Prestine DT one, but this is outdated.  That is going to have to change as I have committed this project to @types only. Almost everyone complains about DT is outdated.  

I am going to make these changes unless someone objects.  I know changes might be bad, but do you want to wait 6 months for another DT update? I would rather have parity between the 2 files so that we are passing at DT quality, yet continue to resolve concerns here.  

Please advise me.  I have committed to an "@types only" acquisition process.

**Comment by yahiko00** [comment]
For 1), as a transitional solution, you could maybe let a _pixi.d.ts_ (deprecated) file and duplicate it to a new official _index.d.ts_.

**Comment by yahiko00** [comment]
I am not a git expert, but I think it is risk free to duplicate your current master branch as v3.x.

Then, this should be possible, checks are needed, to merge your v4.x branch into the master one.

**Comment by clark-stevenson** [comment]
It seems that updates are now few and far between. With v5 a new strategy will be needed, but for now they will remain separate.  Thanks anyway Yahiko.
