### ISSUE TITLE
renderer.backgroundColor removed??

### ISSUE THREAD

**Issue by RyanPridgeon** [pixijs/pixi-typescript#166]
https://github.com/pixijs/pixi-typescript/commit/f8c2defed905e29130eea61fab2b551187448e3d#diff-52caed2d9b9196ced31d99095bcb8a59L827

Why was this property removed? If I use the older version of the types with the latest pixi I can still use backgroundColour fine, and it's documented e.g http://pixijs.download/release/docs/PIXI.WebGLRenderer.html

**Comment by clark-stevenson** [comment]
Sorry about that, I can't look at this for a couple of weeks as on vacation. You could make a PR and I am sure @ivanpopelyshev could merge in the mean time

**Comment by clark-stevenson** [comment]
Thanks guys 👍 I PR'd to DT too.
