### ISSUE TITLE
Class Application seems missing

### ISSUE THREAD

**Issue by yahiko00** [pixijs/pixi-typescript#169]
As far as I can tell, there is an Application class in PixiJS: http://pixijs.download/release/docs/PIXI.Application.html

However, this class seems missing in the definition file.

EDIT: It seems the branch **master** is not the one to take now but the branch **v4.x**.

**Comment by clark-stevenson** [comment]
Did you get the latest version from @types?

It should be available

https://github.com/pixijs/pixi-typescript/blob/v4.x/pixi.js.d.ts#L211

**Comment by clark-stevenson** [comment]
Yes!

**Comment by clark-stevenson** [comment]
Do you know how I should make this the default?

I don't like this repo pointing to the ancient v3 and dislike having to go to the v4/ branch.

**Comment by yahiko00** [comment]
Well, first I used @types, but not up to date at this moment.
Then I used pixijs/pixi-typescript but the branch master
And now I am using pixijs/pixi-typescript#v4.x

But I am still ok :)

If npm now point to v4.x, it would be maybe more consistent to make v4.x your master branch.

**Comment by clark-stevenson** [comment]
I totally agree! It is my fault that you had this effort but I am not 100% sure how to solve it. It will be part of #165 Glad you found a solution 👍
