### ISSUE TITLE
PIXI.mesh.Geometry and RawMesh missing

### ISSUE THREAD

**Issue by yahiko00** [pixijs/pixi-typescript#171]
According to the documentation, classes `Geometry` and `RawMesh` exist in the namespace `PIXI.mesh`: http://pixijs.download/release/docs/PIXI.mesh.Geometry.Geometry.html
http://pixijs.download/release/docs/PIXI.mesh.RawMesh.html

However, it seems they are missing in the declaration file.

**Comment by englercj** [comment]
These are for v5, an unreleased version. It is an error that these docs contain those classes.

@bigtimebuddy Can we fix the docs for the `release` tag? Looks like that v5 alpha made it in.

**Comment by yahiko00** [comment]
Okie Dookie. I feel I need to switch to this v5... Is it safe enough? :P

**Comment by ivanpopelyshev** [comment]
You can use it to experiment with shaders, but make your own typings for it. Or wait some time, i'll provide my TS version of v5 soon.

**Comment by clark-stevenson** [comment]
Sounds interesting 💃  Are you going to try to mirror development or is the Pixi Codebase going TS?

**Comment by yahiko00** [comment]
Here are my typings for `Attributes`, `Geometry` and `Buffer`. Not sure they are accurate, but it can be a comparison point:
```ts
declare namespace PIXI {
    export class Buffer {

        constructor(size: number);

        float32View: Float32Array;
        uint32View: Uint32Array;

        destroy(): void;

    }
    declare namespace mesh {
        export class Attribute {

            constructor(buffer: string, size?: number, normalised?: boolean, type?: number, stride?: number, start?: number, instance?: boolean);

            destroy(): void;

            static from(buffer: string, size?: number, stride?: number, start?: number, normalised?: boolean): Attribute;

        }

        export class Geometry {

            constructor(buffers?: number[], attributes?: any);

            buffers: number[];
            attributes: any;
            glVertexArrayObjects: any;
            id: number;
            instanced: boolean;
            instanceCount: number;
            _size: number | null;

            addAttribute(id: string, buffer: Buffer | number[], size?: number, normalised?: boolean, type?: number, stride?: number, start?: number, instance?: boolean): Geometry;
            getAttribute(id: string): Attribute;
            addIndex(buffer: Buffer | number[]): Geometry;
            getIndex(): Buffer;
            interleave(): Geometry;
            getSize(): number;
            destroy(): void;
            clone(): Geometry;
            static merge(geometries: Geometry[]): Geometry;

        }
    }
}
```

**Comment by englercj** [comment]
> Okie Dookie. I feel I need to switch to this v5... Is it safe enough? :P

No, the library architecture for v5 hasn't even been designed fully yet, much less written. The v5 alpha thing that came out was simply a testing ground for the proposed Geometry API. The release version of v5 will bear little resemblance to that tag.

**Comment by yahiko00** [comment]
Good to know. So I'd better not to rely on anything that comes from this v5 alpha if I understand?

**Comment by bigtimebuddy** [comment]
@yahiko00, yes that's correct.

**Comment by clark-stevenson** [comment]
I don't think there is anything to do in this particular ticket here.
