### ISSUE TITLE
Render Options Background Color is number instead of string

### ISSUE THREAD

**Issue by JCWardle** [pixijs/pixi-typescript#174]
Hi,

I noticed that the background color property on RENDER_OPTIONS is a number and I think it should be a string. This shows how it works in the source code https://github.com/pixijs/pixi.js/blob/master/src/core/renderers/SystemRenderer.js#L166-L186

**Comment by englercj** [comment]
You [misread](https://github.com/pixijs/pixi.js/blob/f3da834ccb6ef7fd2470aa4960fa9b79ef0f298a/src/core/renderers/SystemRenderer.js#L175). It is assigned to [`options.backgroundColor`](https://github.com/pixijs/pixi.js/blob/f3da834ccb6ef7fd2470aa4960fa9b79ef0f298a/src/core/renderers/SystemRenderer.js#L38), which is a number, or to [`this._backgroundColor`](https://github.com/pixijs/pixi.js/blob/f3da834ccb6ef7fd2470aa4960fa9b79ef0f298a/src/core/renderers/SystemRenderer.js#L157), which is the default and also a number. The property is also defined [as a number](https://github.com/pixijs/pixi.js/blob/f3da834ccb6ef7fd2470aa4960fa9b79ef0f298a/src/core/renderers/SystemRenderer.js#L307).

**Comment by JCWardle** [comment]
Yep my mistake. Thanks for clearing it up.

**Comment by englercj** [comment]
Anytime, thanks for contributing it is always appreciated!
