### ISSUE TITLE
Typo in PIXI.Transform properties

### ISSUE THREAD

**Issue by qtiki** [pixijs/pixi-typescript#180]
I think there's a typo in PIXI.Transform properties:

The [_nsx](https://github.com/pixijs/pixi-typescript/blob/896a7b2fa73882f09a6f1ff8099a521c2ce224a1/pixi.js.d.ts#L422) in types should be [_sx](https://github.com/pixijs/pixi.js/blob/07f6313a6cbe4ab83c7df2f48412874e3fd81b58/src/core/display/Transform.js#L58) instead.

Even though the property is protected this causes problems when extending the Transform with a custom type.

**Comment by ivanpopelyshev** [comment]
Its not a typo, there was _nsx in transform before i refactored it, it was negation, thats why "n". Yeah, we has to fix it in typings :)

**Comment by clark-stevenson** [comment]
Thanks guys 😄
