### ISSUE TITLE
PIXI.DisplayObject.hitArea, return type HitArea missing

### ISSUE THREAD

**Issue by Chuckame** [pixijs/pixi-typescript#184]
According to the documentation, field hitArea in PIXI.DisplayObject can be type of PIXI.Rectangle | PIXI.Circle | PIXI.Ellipse | PIXI.Polygon | PIXI.RoundedRectangle : 
http://pixijs.download/release/docs/PIXI.DisplayObject.html#hitArea

But when this field is used (by InteractionManager), only hitArea.contains(x,y) is called, corresponding to interface HitArea.
So it's useful when you want to do hit area based on transparency.

**Comment by ivanpopelyshev** [comment]
right, that's the interface we need

**Comment by clark-stevenson** [comment]
I simply need to add `PIXI.HitArea` to `DisplayObject` ?

`hitArea:  PIXI.Rectangle | PIXI.Circle | PIXI.Ellipse | PIXI.Polygon | PIXI.RoundedRectangle | PIXI.HitArea`

**Comment by ivanpopelyshev** [comment]
either that, either set only HitArea and add "implements HitArea" to all of those things,

**Comment by clark-stevenson** [comment]
I was almost sure shapes implemented HitArea, I have no idea why I removed that at some point! 

Anyway as you said I will `implements HitArea` on shape geometry.

I just wonder, in general, is it a good idea to keep the list of union types or is it clutter? Like, if I make the property:

`hitArea: PIXI.HitArea` 

It isn't clear that actually there are several built in geometry objects here. Whereas this:

`hitArea: PIXI.Rectangle | PIXI.Circle | PIXI.Ellipse | PIXI.Polygon | PIXI.RoundedRectangle | PIXI.HitArea` gives you some options without leaving the IDE.

I am aware this is a generic question in general programming but I don't really know the answer :/

**Comment by ivanpopelyshev** [comment]
Agree, we should leave like it is + add hitarea.

**Comment by clark-stevenson** [comment]
Thanks lads!

I will update DT at the end of the week.

**Comment by Chuckame** [comment]
Thx guys, loving you !
