### ISSUE TITLE
CanvasExtract#pixels() and WebGLExtract#pixels(), bad return type

### ISSUE THREAD

**Issue by Chuckame** [pixijs/pixi-typescript#185]
According to the documentation, method pixels() must return Uint8ClampedArray :
http://pixijs.download/release/docs/PIXI.extract.CanvasExtract.html#pixels

Or in types def :
pixels(renderTexture?: DisplayObject | RenderTexture): number[];

**Comment by ivanpopelyshev** [comment]
Yep

**Comment by ivanpopelyshev** [comment]
But that's only for CanvasExtract, Webgl returns different thing. So, ArrayLike<number> will be better there.

**Comment by clark-stevenson** [comment]
Thanks guys 💃 

So this is now:


```
namespace extract {
        class CanvasExtract {
            protected renderer: CanvasRenderer;

            constructor(renderer: CanvasRenderer);

            image(target?: DisplayObject | RenderTexture): HTMLImageElement;
            base64(target?: DisplayObject | RenderTexture): string;
            canvas(target?: DisplayObject | RenderTexture): HTMLCanvasElement;
            pixels(renderTexture?: DisplayObject | RenderTexture): number[];

            destroy(): void;
        }
        class WebGLExtract {
            protected renderer: WebGLRenderer;

            constructor(renderer: WebGLRenderer);

            image(target?: DisplayObject | RenderTexture): HTMLImageElement;
            base64(target?: DisplayObject | RenderTexture): string;
            canvas(target?: DisplayObject | RenderTexture): HTMLCanvasElement;
            pixels(renderTexture?: DisplayObject | RenderTexture): number[];

            destroy(): void;
        }
    }
```


- http://pixijs.download/release/docs/PIXI.extract.CanvasExtract.html#pixels
- http://pixijs.download/release/docs/PIXI.extract.WebGLExtract.html#pixels

They both do indeed seem to have Uint8ClampedArray as returns as originally stated?

So should I change both to `Uint8ClampedArray`?

**Comment by Chuckame** [comment]
@ivanpopelyshev, I saw the code, it is WebGLExtract.html # pixels (): UInt8Array!
But I use it with Uint8ClampedArray actually in WebGLExtract, and no error thrown: D (soooo ugly)

So:
CanvasExtract # pixels returns Uint8ClampedArray
WebGLExtract # pixels returns Uint8Array

Same methods, exactly the same ... That's the reason TS does not warning.

(Maybe a future TS update?)

**Comment by ivanpopelyshev** [comment]
UInt8ClampedArray is different a bit, I cant pass it as a UInt8Array to webgl, so there's difference. I dont know what to do with it, may be leave ArrayLike<number> ? its user problem.

**Comment by Chuckame** [comment]
Yep yep, but if two classes have exactly the same methods and fields, they are physically the same for javascript (Not in methods execution, obviously), this is what I mean.
Bref,
UInt8Array for webgl and UInt8ClampedArray for canvas, so methods have a bad returns, it's not number[].

**Comment by clark-stevenson** [comment]
This change is OK?

**Comment by Chuckame** [comment]
Fine, thanks
