### ISSUE TITLE
Sprite.removeAllListeners argument 'event' should be optional

### ISSUE THREAD

**Issue by nitwhiz** [pixijs/pixi-typescript#189]
**There**
https://github.com/pixijs/pixi-typescript/blob/fb818b819b0ca698dee174114486a9ff6f53eedc/pixi.js.d.ts#L392

**Because**
https://nodejs.org/api/events.html#events_emitter_removealllisteners_eventname

**Comment by clark-stevenson** [comment]
Thanks! Sorry for the long delay 💃
