### ISSUE TITLE
Does this project keep synchronize with PixiJS (js version) v5?

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi-typescript#199]

**Comment by bigtimebuddy** [comment]
We added typings to v5 directly for pixi.js and pixi.js-legacy packages.

**Comment by clark-stevenson** [comment]
I have been drifting away from being able to use Pixi at the moment so have fallen out of the loop.  I just try to maintain v4 at the moment.  

How did you end up creating the v5 typings in the end?  Are they still Manual, or did anyone ever find a "JSDoc to TS" tool?

Just interested 👍

**Comment by bigtimebuddy** [comment]
No magic tool yet for generating typings. But hopefully we’ll come up with a solution soon.

**Comment by englercj** [comment]
> did anyone ever find a "JSDoc to TS" tool?

I've been working on one for a bit, please contribute if you find issues or need features. https://github.com/englercj/tsd-jsdoc

**Comment by clark-stevenson** [comment]
Made it clear in the readme that this is for v4.x
