### ISSUE TITLE
Container.getChildByName() return type: null is missing

### ISSUE THREAD

**Issue by WCNUA** [pixijs/pixi-typescript#201]
For now `getChildByName()` return type is `DisplayObject`:
`...`
`    class Container extends DisplayObject {`
`        // begin extras.getChildByName`
`        getChildByName(name: string): DisplayObject;`
`        // end extras.getChildByName`
`...`

But if `name` parameter is wrong (container doesn't contain a child with such name) it returns `null`.
So I'd suggest to extend return type to `DisplayObject | null`

**Comment by ivanpopelyshev** [comment]
I'm afraid there are so many places like this, whole module is not null-safe.

**Comment by WCNUA** [comment]
Come'on, guys. Let's make it better ;)

**Comment by clark-stevenson** [comment]
@WCNUA 

Do you know of any good strategy to deal with that? The majority of the declaration was created before TypeScript 2.0 and `strictNullChecks` wasn't an option.  I am just concerned that unless I have a full range of tests in place to check for these, and I am 100% confident in that,  people are going to end up with null errors all over their code with the next update for the ones that were missed. 

👍

**Comment by clark-stevenson** [comment]
It is unlikely this will be fixed for V4 branch 😞
