### ISSUE TITLE
DisplayObject.trackedPointers is not a function

### ISSUE THREAD

**Issue by apptaro** [pixijs/pixi-typescript#203]
DisplayObject.trackedPointers is not a function, but a property.

https://github.com/pixijs/pixi-typescript/blob/v4.x/pixi.js.d.ts#L344

**Comment by clark-stevenson** [comment]
@apptaro 

Thanks! 👍 

I have made a PR to DT. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30228

Hopefully it will be merged later today.  

Appreciated.
