### ISSUE TITLE
how are you generating your d.ts?

### ISSUE THREAD

**Issue by macguffin** [pixijs/pixi-typescript#209]
Hi just wondered if you are using any specific tools to automate the generation of your d.ts files.

Thanks

**Comment by clark-stevenson** [comment]
Hey @macguffin nope.  Such a thing has been discussed before, and will likely have to exist for Version 5 of Pixi. 

Would you be able to shed any light on this process or experience with any tools?

**Comment by macguffin** [comment]
https://github.com/TypeStrong/dts-bundle

I have used this attached to a webpack config and it seems ok-ish but that is just combining all the d.ts files generated by typescript.

Your d.ts is much nicer though and I was hoping you had found a better tool. Do you do it by hand?

**Comment by englercj** [comment]
> Do you do it by hand?

Yes, this project is maintained by hand.
