### ISSUE TITLE
Seems to be a bit behind Pixi

### ISSUE THREAD

**Issue by johnfn** [pixijs/pixi-typescript#21]
For instance, according to the latest Pixi docs, you can now use a PixiRenderer to render any Container, not just a Stage. However, this is not allowed by these definitions.

Additionally, DisplayObjectContainer has been renamed to Container. 

I'd be happy to help, but I'm not quite sure which version of Pixi this is up to date with.

**Comment by clark-stevenson** [comment]
Hey @johnfn 

The latest version of master should work with the master pixi or dev pixi versions. Right now the definitions follow the dev branch. 

https://github.com/pixijs/pixi-typescript/blob/master/pixi.js.d.ts

**Comment by johnfn** [comment]
Ah, my bad - I was looking at the Phaser Pixi definition file and for somehow got that one mixed up with this one. Thanks!
