### ISSUE TITLE
Event type broken for Container on/once callbacks

### ISSUE THREAD

**Issue by qtiki** [pixijs/pixi-typescript#210]
The on/once callback type is correct for `DisplayObject` but broken for `Container`: https://github.com/pixijs/pixi-typescript/blob/a71496d6c48cab9c9e81293433a6c00230e0e958/pixi.js.d.ts#L298

The callback type for `DisplayObject` is `(event: interaction.InteractionEvent) => void` but for `Container` it is `(displayObject: DisplayObject) => void`. The first parameter for the callback is an `InteractionEvent` so that seems to be broken.

**Comment by clark-stevenson** [comment]
Hey @qtiki thank you 👍 

I am temporarily underwater and hope I can take a look as soon as I can, but this seems like one of the most recent PR's 

https://github.com/pixijs/pixi-typescript/pull/208

@julien-moreau

Any quick suggestions?

**Comment by qtiki** [comment]
I was trying to go back to see when the error was introduced but I couldn't find it easily. It wasn't caused by that #208 PR at least.

**Comment by qtiki** [comment]
It seems the bug has been around for over 2 years: https://github.com/pixijs/pixi-typescript/commit/19fc52eddf0287ca018721a128cf91b70b1aad01

The fix in #208 PR only surfaced it because prior to that the typing did not work properly for events other than `added` and `removed`.

**Comment by clark-stevenson** [comment]
@qtiki 

I agree something is not right

I made a basic angular app just as it was on hand, in the app.component.ts it is easy enough to follow.

https://stackblitz.com/edit/angular-alx6bb

It would seem that `added` and `removed`  use the callback `fn: (container: Container) => void` 

Whereas, the other events such as click have  `fn: (event: InteractionEvent) => void`

Is this what you would also expect?

**Comment by julien-moreau** [comment]
If the callbacks's argument is always an "**InteractionEvent**" for a Container, then it should be fixed for sure as it is always an "**InteractionEvent**" according to the "**interactionManager**" class

@qtiki would be awesome if you can PR :)

**Comment by julien-moreau** [comment]
@qtiki, created the pull request: https://github.com/pixijs/pixi-typescript/pull/211

**Comment by clark-stevenson** [comment]
Thanks Julien, I waited a while but merged it as I didn't see any harm.

**Comment by julien-moreau** [comment]
That’s cool, thanks :)
