### ISSUE TITLE
PIXI.display not defined

### ISSUE THREAD

**Issue by carrascodev** [pixijs/pixi-typescript#212]
PIXI.display is not defined therefore I can't test some things that I am trying to do :/

**Comment by clark-stevenson** [comment]
Hey @carrasco39 👍 

Are you using Version 5?

**Comment by carrascodev** [comment]
No, I'm using version 4 but I was googling here and it seems its a package apart from pixi.js itself, am I wrong?

**Comment by clark-stevenson** [comment]
Ahh I haven't use it.  I would have expected these to be picked up in the package as it comes with Types:

https://github.com/pixijs/pixi-display/blob/layers/dist/pixi-layers.d.ts

**Comment by ivanpopelyshev** [comment]
First comment in layers examples:

```js
// This is demo of pixi-display.js, https://github.com/gameofbombs/pixi-display
```

https://github.com/pixijs/pixi-display

**Comment by carrascodev** [comment]
Awesome, sorry for the disturbance
