### ISSUE TITLE
PIXI.sound.play() is undefined

### ISSUE THREAD

**Issue by smival** [pixijs/pixi-typescript#215]
```
"dependencies": {
      "@types/node": "^11.11.3",
      "@types/pixi.js": "^4.8.6",
      "pixi.js": "^4.8.6",
      "pixi-sound": "^2.1.0"
    }
```

code

```
import * as PIXI from 'pixi.js';
import * as snd from 'pixi-sound';

PIXI.loader.add([
    {name:'music', url:'music.ogg'}
        ])
.load((loader, resources) => 
{
    PIXI.sound.play('music');
});

```
I tried to use PIXI.loader.resources.music.data.play();, is works but stop() func also throws "property 'stop' of undefined" error

**Comment by clark-stevenson** [comment]
@smival 

Forgive me for the delay.   I think this is related to [pixi-sound](https://github.com/pixijs/pixi-sound/issues)

**Comment by msqaddura** [comment]
```
import * as PIXI from "pixi.js";
import SOUND from "pixi-sound";

PIXI["s" + "o" + "u" + "n" + "d"] = SOUND; // ts wont complain
```

best hack ever! :D :D

**Comment by ghost** [comment]
Excellent hack, but why the hell does it work?

**Comment by msqaddura** [comment]
Basically it means import and use, if the import is not used anywhere in the file then it will not be included in the trans-piled file, as a duty of tree-shaking. so you can do console.log(SOUND) or PIXI["s"+"o..... . as long as you use it, it should be fine

**Comment by ghost** [comment]
Thanks! That makes perfect sense! :-)
