### ISSUE TITLE
Wrong loader enum location in 4.8.7 version

### ISSUE THREAD

**Issue by ivanpopelyshev** [pixijs/pixi-typescript#220]
@clark-stevenson 

Here: https://github.com/pixijs/pixi-typescript/commit/c40a4634b8be7669b19d92e2536ee2fd32d75681

As far as i know, `Resource.TYPE` and other enums are still inside the `PIXI.loaders.Resource` and nlot in `PIXI.loaders`

Please fix & republish 4.8.8 as the penalty :)

**Comment by clark-stevenson** [comment]
😅 I knew messing with the loader would be troublesome but thought I escaped.

You are right, I can move them back to Resource Class as static like they used to be since I don't think I can put an enum on a class.  Will do it asap

**Comment by ivanpopelyshev** [comment]
Wait! ugh.

I have workaround for enums in class, but resource has to be interface in that case: https://github.com/pixijs/pixi.js/blob/dev/types/loader.d.ts#L89

We can do that because Resource is never created manually, only through Loader.

**Comment by clark-stevenson** [comment]
Merged!
