### ISSUE TITLE
Replace with Definitely Typed version

### ISSUE THREAD

**Issue by clark-stevenson** [pixijs/pixi-typescript#224]
For a long time there is been annoyance where @types/pixi.js  has been deviating from this repo for some time.  This has created 2 almost identical type files, in different syntax formats.  It is just a legacy issue but I would like to resolve it.

I will rename the latest version of this declaration and place it in `temp` with no extension just incase all of this goes wrong fast although it will no longer receive updates from this date. 

I will replace that with the declaration from DT and this will make everything much easier to keep sync.

**Comment by ivanpopelyshev** [comment]
Do as you want, we believe in you :) pixi-js v4 typings are in good hands!

**Comment by clark-stevenson** [comment]
Thanks Ivan!  I was happy to see over in Pixi that a TypeScript direction is in the works! 😀 

I made the change,  DT and this file contents are identical and now I will wait to see if the world explodes.
