### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by user471** [pixijs/pixi-typescript#26]
`pixi.js.d.ts` should contain JSDoc from the `pixi.js`

**Comment by clark-stevenson** [comment]
There was a guy on Phaser who weaved documentation from Phaser into the build process of `phaser.d.ts` resulting in `phaser-comments.d.ts`.

No idea how he did it but would not attempt this manually. 
- It becomes a project on the accuracy of the docs not the `d.ts` which is what has value. 
- It makes it hard to maintain. Adding thousands of lines of obscurity and making it difficult to simply compare JS/TS Api as part of the manual process.

The best solution of all would be to generate this whole `d.ts` file from the Docs and we become documentation enforcers which would benefit everyone but the mechanisms for this doing this are beyond my skillset and from my experience, have not found any projects doing this.  

Would definitely appreciate anyone else's thoughts.

**Comment by englercj** [comment]
> The best solution of all would be to generate this whole d.ts file from the Docs

I've been wanting to do this for ever. Maintain the docs in code properly, and all the other things will flow from that.

**Comment by clark-stevenson** [comment]
This won't happen until we can generate the declaration from JS in some automated way.
