### ISSUE TITLE
Allow AbstractFilter as shader

### ISSUE THREAD

**Issue by oal** [pixijs/pixi-typescript#27]
I didn't open a pull request for this yet, as I'd like to hear from someone more knowledgeable about Pixi first.

Sprites etc. work fine when you assign a filter (AbstractFilter descendant) to their shader property. From what I can understand, extending AbstractFilter is in many cases easier than writing a custom shader. Is there any technical reason to not want to do this?

If there isn't, then it should be allowed using `Shader | AbstractFilter` instead of just `Shader`, here: https://github.com/pixijs/pixi-typescript/blob/master/pixi.js.d.ts#L874 (and the other descendants of Container that allow for shaders to be set)

**Comment by englercj** [comment]
That should definitely be `Shader | AbstractFilter`.

**Comment by clark-stevenson** [comment]
Thanks for this guys.
