### ISSUE TITLE
PIXI.Stage is not defined

### ISSUE THREAD

**Issue by ddennis** [pixijs/pixi-typescript#3]
Hi 

I am trying to use PIXI with typescript, it seems PIXI.Stage() is not defined in the type definition.

/Dennis

**Comment by clark-stevenson** [comment]
Hey mate, 

Are you using Pixi 2? If so check out the v2 branch here. 

Pixi 3 I believe has no stage, but rather a Pixi Container which one would use as a stage.

`var stage = new PIXI.Container()`

**Comment by ddennis** [comment]
Sorry - my mistake.
I am having some problems getting pixi v3 to work with typescript's external modules. 
I did not get the "You do not need to use a PIXI Stage any more, you can simply render any container." before now.

Thanks 
Dennis
