### ISSUE TITLE
Property 'addPixiMiddleware' does not exist on type 'typeof Loader'.

### ISSUE THREAD

**Issue by Relic** [pixijs/pixi-typescript#40]
Attempting to use PIXI.loaders.Loader.addPixiMiddleware function (found [here](https://github.com/pixijs/pixi.js/blob/v3.0.10/src/loaders/loader.js)) but it produces the error in the title.

Seems like the TypeScript definition is defining Loader as the one in the Resource Loader project (which the pixi Loader extends).

**Comment by clark-stevenson** [comment]
Noted, I will check it out asap this week. Thanks for letting me know.  The external dependencies tend to be a bit lame as its tough to keep up.

**Comment by clark-stevenson** [comment]
I will see if I can sort this relationship out better for v4

For now I added the `addPixiMiddleware` as a static method to the Loader.
