### ISSUE TITLE
Version 4 Support?

### ISSUE THREAD

**Issue by tdreyno** [pixijs/pixi-typescript#53]

**Comment by clark-stevenson** [comment]
Do you have any idea how I could use github to see a list of all changes between 3.0.11 and 4.1.0?

**Comment by englercj** [comment]
Compare view:

https://github.com/pixijs/pixi.js/compare/v3.0.11...dev

But, I'm sure the diff is too big to be shown in a single compare.

**Comment by clark-stevenson** [comment]
Thanks Chad :dancer:

**Comment by tdreyno** [comment]
Thanks for your hard work. Looking forward to upgrade our v3 app (http://unfiltered.news) to v4 :)

**Comment by clark-stevenson** [comment]
[v4.x](https://github.com/pixijs/pixi-typescript/tree/v4.x)

The worse of it is done, but it is completely untested and would probably avoid using it for the rest of the month until I can get some real tests written and do another pass of the code.

The `depreciations` file is not yet done either so on a v3 project, will probably be full of problems.
