### ISSUE TITLE
Problem with using pixi.js module with typescript ... getting error about module augmentations

### ISSUE THREAD

**Issue by dnassler** [pixijs/pixi-typescript#54]
Hi. I am very new to typescript and and struggling to understand how to get the Pixi.js node module to work in my test project. I'm playing around with an angular2 seed project (https://github.com/angular/angular2-seed) and added a Pixi reference (added a new component that tries to import pixi.js) to see if I could get it to work. 

So I installed the typings like so:

`typings install pixi.js=github:pixijs/pixi-typescript/pixi.js.d.ts#08306a3`

Then I have a file "pixiExp.ts" where I refer to the pixi.js module. I do the following:

```
import * as PIXI from 'pixi.js';
... other stuff here ...
renderer = PIXI.autoDetectRenderer(256,256);
...
```

It seems to work. But I'm getting a compilation error with regards to the typing definition for pixi:

```
ERROR in [default] /Users/dnassler/dev/angular2/angular2-seed-pixi/typings/browser/definitions/pixi.js/index.d.ts:1856:4 
Exports and export assignments are not permitted in module augmentations.
```

The error has to do with the following (where line 1856 is the line with the "export =" statement):

```
module 'pixi.js' {
    export = PIXI;
}
```

Maybe an irrelevant detail is that I have another "import 'pixi.js'" in a vendor.ts file elsewhere in the project. I don't think that is relevant to the problem but I just thought I'd mention it. Something else to note is that this project is using webpack but that is irrelevant to the specific issue/error I'm getting I think.

Some other details that are irrelevant to the problem but that were necessary for me to get the angular2-seed project to compile with pixi.js.... I had to npm install transform-loader and modify the webpack.config.js file as indicated here https://gist.github.com/mjackson/ecd3914ebee934f4daf4 . In particular I had to add a postLoaders config that uses the transform-loader to handle some "fs" related compile errors. But this is irrelevant to my problem :) 

Does anyone have any ideas? I'm new to typescript so possibly I'm doing something very dumb?

Thanks for anyone's help!

**Comment by dnassler** [comment]
Ok I've eliminated the problem by modifying the pixi.js.d.ts in the area that had the ERROR.... This is what makes the compile error go away:

```
export = PIXI;

// module 'pixi.js' {
//     export = PIXI;
// }
```

Is this ok? It seems ok but since I'm new to Typescript I'm not yet confident about it or any of this.

Regards

**Comment by dnassler** [comment]
Oh, I just tried to uninstall my pixi.js typings then did a reinstall by doing the following and it seems to work better this way and is easier...

```
typings uninstall pixi.js
typings install pixi.js --save --ambient
```

Whereas before I was installing the typings for pixi.js incorrectly by doing:
`typings install pixi.js=github:pixijs/pixi-typescript/pixi.js.d.ts#08306a3 --save`

The reason why I was doing it that way is because when I did:
`typings install pixi.js --save`

I got an error saying that the typings for pixi.js could not be found. But I guess I was missing the "--ambient" flag.

I guess this should be clearer in the readme for this repo? Anyways, I guess it works now. I'm just not sure what --ambient does or why it is needed exactly.

**Comment by clark-stevenson** [comment]
I was hoping to sit down and get to the bottom of this stuff but I am pretty lost. Kind of finding it difficult to find any details (That I understand).

**Comment by clark-stevenson** [comment]
I hope to look at this soon because I think this has changed as well.  `--ambient` I think has changed to `--global` as far as I can tell which I think has something to do with "if you are using a script tag" and that "all definitely typed definitions are global at this time".  I am on a work project where I will need to pull out `Typings` since the old one was using `tsd` but hopefully I can get to the bottom of it.

**Comment by clark-stevenson** [comment]
This is resolved with `npm install @types/pixi.js`. 

`typings` is no longer officially supported unless there have been changes on that side to reflect the modern method of type acquisition which replaces it.
