### ISSUE TITLE
Overloads in definitions

### ISSUE THREAD

**Issue by whizzkid** [pixijs/pixi-typescript#57]
concerning pixi.d.ts for **v4.x**

Having trouble with overloads in the definition file. 

I have a class in typescript

```
export default class LayoutContainer extends PIXI.Container
```

Now I want to override addChild so I can do something before adding the child..
After some fiddling, I got rid of compile errors like 
`Error:(9, 22) TS2415: Class 'LayoutContainer' incorrectly extends base class 'Container'.
 Types of property 'addChild' are incompatible.
 Type '(child: DisplayObject) => DisplayObject' is not assignable to type '{ (child: DisplayObject): DisplayObject; (...child: DisplayObject[]): DisplayObject[]; }'.
 Type 'DisplayObject' is not assignable to type 'DisplayObject[]'.`

So after some fiddling, the following code has no errors, but, I can't seem to implement the correct code for the first overload (the one with ...child and displayObject[] )

```
    public addChild(...child: PIXI.DisplayObject[]): PIXI.DisplayObject[];
    public addChild(child:PIXI.DisplayObject):PIXI.DisplayObject;
    public addChild(child:PIXI.DisplayObject | PIXI.DisplayObject[]):any
    {
        this.needsLayout = true; // (this is all i want to do extra. boohoo)
        if (child instanceof  PIXI.DisplayObject)
        {
            return super.addChild(child);
        }
    }
```

Does anyone know how to properly do this?

Please don't focus on the this.needsLayout bits, I could do it in a different way, but the issue is, how to properly override a function that has oveloads..

**Comment by whizzkid** [comment]
also, right before going home.
I think the definition file is incorrect.

```
        addChild(child: DisplayObject): DisplayObject;
        addChild(...child: DisplayObject[]): DisplayObject[];
```

because when you use multiple children,  the actual addChild function doesn't return the ...child, it ALWAYS returns 'child'.. so if multiple children are used.  addChild uses the arguments object. but returns the child param (which is the first child used)...

thoughts?

pff..  time for weekend..

**Comment by clark-stevenson** [comment]
Man I appreciate you looking into this.

I mentioned this in Slack to the team on the day that you asked it (Because it blew my mind).

But having read the answer, and having read your ticket.  I am still not 100% sure how to deal with it. 

Does it simply mean, at the very end of the day, that we have a single method perhaps? 

`addChild(...child: DisplayObject[]): DisplayObject`

**Comment by whizzkid** [comment]
As far as I understand it, yeah.
Javascript doesn't actually support overloading, so it all ends up in 1 function, that looks at the provided arguments and performs its code depending on that..  
In the definition files you can define what typescript will accept and code-complete.

But I don't understand how you can have several different return types. (without typescript errors)
Now addChild is a wrong example. because the code right now isn't very neat or logical in its returns.

But lets imagine it was corrected and adding 1 child returns 1 child, and adding multiple children will return an array of children..   I don't know how to correctly implement this without typescript throwing errors...

pixi.d.ts

```
addChild(child: DisplayObject): DisplayObject;
addChild(...child: DisplayObject[]): DisplayObject[];
```

I started in my own class which extends PIXI.Container

```
    public addChild(child:PIXI.DisplayObject):PIXI.DisplayObject;
    public addChild(...child: PIXI.DisplayObject[]): PIXI.DisplayObject[];
    public addChild(child:PIXI.DisplayObject | PIXI.DisplayObject[]):PIXI.DisplayObject | PIXI.DisplayObject[]
    {
        this.needsLayout = true;  // my custom code for this class
        if (child instanceof PIXI.DisplayObject)
        {
            return super.addChild(child);
        }
    }
```

this is in my current code (because I never use the multiple params version anyway)

but I tried this:

```
    public addChild(child:PIXI.DisplayObject):PIXI.DisplayObject;
    public addChild(...child: PIXI.DisplayObject[]): PIXI.DisplayObject[];
    public addChild(child:PIXI.DisplayObject | PIXI.DisplayObject[]):PIXI.DisplayObject | PIXI.DisplayObject[]
    {
        this.needsLayout = true; // my custom code for this class
        if (Array.isArray(child))
        {
            return super.addChild(...child);
        }
        else if (child instanceof PIXI.DisplayObject)
        {
            return super.addChild(child);
        }
    }
```

this compiles... (but doesn't work, because when you do 
`addChild(child1,child2,child3)`
child in the addChild function is still  child1... not an array

So I tried this:

```
        public addChild(child:PIXI.DisplayObject):PIXI.DisplayObject;
    public addChild(...child: PIXI.DisplayObject[]): PIXI.DisplayObject[];
    public addChild(child:PIXI.DisplayObject | PIXI.DisplayObject[]):PIXI.DisplayObject | PIXI.DisplayObject[]
    {       
        this.needsLayout = true;
        if (arguments.length>1)
        {
            return super.addChild(...child);  //  <- this is the line of the error stated below.
        }
        else if (child instanceof PIXI.DisplayObject)
        {
            return super.addChild(child);
        }
    }
```

which gives me:

```
Error:(63, 29) TS2461: Type 'DisplayObject | DisplayObject[]' is not an array type.
```

Soooooo. I have no clue how to properly do it should I ever need it.

**Comment by whizzkid** [comment]
oh by the way, 

```
public addChild(child:PIXI.DisplayObject | PIXI.DisplayObject[]):PIXI.DisplayObject | PIXI.DisplayObject[]
    {
        this.needsLayout = true;
        return super.addChild(child);
    }
```

gives me this error:
`Error:(68, 26) TS2345: Argument of type 'DisplayObject | DisplayObject[]' is not assignable to parameter of type 'DisplayObject'.
 Type 'DisplayObject[]' is not assignable to type 'DisplayObject'.
 Property '_cacheAsBitmap' is missing in type 'DisplayObject[]'.`

So the typescript compiler does do some checking before you return stuff I think..

**Comment by whizzkid** [comment]
haha, wrong button..

**Comment by clark-stevenson** [comment]
@whizzkid 

I think this is solved.  We now know (and the docs are fixed) that adding many items will always return the FIRST item.

So with that said, the following should be acceptable which is in the latest v4 branch. 

```
addChild(child: DisplayObject): DisplayObject;
addChild(...child: DisplayObject[]): DisplayObject;
```

Feel free to re-open if this does not address the original issue.  :+1:
