### ISSUE TITLE
CanvasSpriteRender / CanvasSpriteRenderer

### ISSUE THREAD

**Issue by webbiesdk** [pixijs/pixi-typescript#64]
When adding all the things you see in #63, i also noticed something strange. 

`CanvasSpriteRenderer` is a new class, which has been added to v4, and in the module system in the JavaScript, it is called `CanvasSpriteRenderer`. But when it is exported to the global object, it is suddenly `CanvasSpriteRender` (without the last "er"): https://github.com/pixijs/pixi.js/blob/b9d6badf9c4805494c43aed96fee9229da0dc659/src/core/index.js#L26
But the declaration file states that it is `CanvasSpriteRenderer` (with the extra "er"), which is not the name it is given when exported to the PIXI object. 

So there is an error, but I'm not sure where it should be fixed. There are 2 options. 

1: Change `CanvasSpriteRenderer` to `CanvasSpriteRender` in the decaration file. 
2: Change the JavaScript file, so that the exported class is `CanvasSpriteRenderer` instead of `CanvasSpriteRender`. (This is the one that I prefer).

**Comment by clark-stevenson** [comment]
Hey @webbiesdk thanks!  Mat pushed a fix which matches your second option and that means no change is required for ts  :+1:
