### ISSUE TITLE
Suggesting change for BaseTexture Constructor

### ISSUE THREAD

**Issue by niokasgami** [pixijs/pixi-typescript#81]
PIXI Version : any 

suggestion : So I work with pixi on typescript but I noticed that what's was a "valid" command in JS is not valid when using the typescript form 

PIXI Typescript definition files I resquest to change : 
`
   constructor(source: HTMLImageElement | HTMLCanvasElement, scaleMode?: number, resolution?:          number);

TO :
`constructor(source?: HTMLImageElement | HTMLCanvasElement, scaleMode?: number, resolution?: number);`

Why?:
simply because normally you can do 
`   

```
var texture = new PIXI.Texture(new PIXI.BaseTexture());
PIXI.Sprite.call(this, texture);`
```

then after you set the texture later on.
it's totally valid in JS but I noticed this wasn't in typescript.
Will be possible in the PIXI V4 to make it as optionnal? for permit to create empty BaseTexture?

thanks for your further answer.

**Comment by clark-stevenson** [comment]
Thanks @niokasgami 

You are [totally correct](https://github.com/pixijs/pixi.js/blob/dev/src/core/textures/BaseTexture.js#L161)! 

I will get this change added as soon as I get home.

**Comment by niokasgami** [comment]
@clark-stevenson  thanks for making change! 
I will close it since it's will be resolved : >
