### ISSUE TITLE
add Optionnal parameters to TilingSprite Constructor

### ISSUE THREAD

**Issue by niokasgami** [pixijs/pixi-typescript#85]
I noticed from the tilingSprite class they have optional parameters for the constructor

those optional parameters are width and height.
`

```
  PIXI.TilingSprite = function(texture, width, height)
   {
   PIXI.Sprite.call( this, texture);

/**
 * The with of the tiling sprite
 *
 * @property width
 * @type Number
 */
this._width = width || 100;

/**
 * The height of the tiling sprite
 *
 * @property height
 * @type Number
 */
this._height = height || 100;
```

`

**Actual DefinitionFile**
`constructor(texture: Texture, width: number, height: number);`

**Proposed change**
`constructor(texture: Texture, width?: number, height?: number);`

PS : BOTH v2 and v4 tilingSprite are REALLY similar for most of them.

**Comment by clark-stevenson** [comment]
Thanks man :+1:   This is added to v4.   I need to figure out what is happening with these older definitions in the next couple of weeks.

**Comment by niokasgami** [comment]
@clark-stevenson  your welcome haha I work on a external library (the rpg maker MV library) and I convert it to typescript for my game and I stomp on those errors so I report them all for help~
Will close it because it's was resolved!
