### ISSUE TITLE
Container's destroy update

### ISSUE THREAD

**Issue by bigtimebuddy** [pixijs/pixi-typescript#86]
This line needs to be updated to reflect Containers new destroy API:
https://github.com/pixijs/pixi-typescript/blob/master/pixi.js.d.ts#L248

``` typescript
destroy(destroyChildren?: boolean): void;
```

See the related PR here:
Container.destroy update: https://github.com/pixijs/pixi.js/pull/2592

``` js
var container = new Container();
// Destroy with options
container.destroy({children: true, texture: true, baseTexture: true});
// Alternatively, short-hand for above
container.destroy(true);
```

Not sure of the syntax here. Someone else should make the PR. 

``` typescript
export interface DestroyOptions {
  children?:boolean,
  texture?:boolean,
  baseTexture?:boolean
}
destroy(destroyChildren?:boolean|DestroyOptions): void;
```

**Comment by clark-stevenson** [comment]
Thanks :+1:  What you wrote was perfect!
