### ISSUE TITLE
pixi-tilemap Support?

### ISSUE THREAD

**Issue by fryedrycestyle** [pixijs/pixi-typescript#87]
Hey there!

I'm so glad there's a Typescript definition repo here, but I was wondering if there was a plan in place to add support for the [pixi-tilemap](https://github.com/pixijs/pixi-tilemap) project? I'm a _bit_ new to Typescript, and am not 100% sure of how easy it is to make one, but I think it would be a great addition!

Thanks,
Cian

**Comment by clark-stevenson** [comment]
Sorry I took so long to reply.  As far as I know, Pixi Tilemap isn't maintained for v4.  I don't have any plans to provide a v3 definition, but if Ivan updates some day, I will for sure add it!  👍

**Comment by ivanpopelyshev** [comment]
Actually, it works in v4 just fine.

There's also special branch https://github.com/pixijs/pixi-tilemap/tree/dev-multitexture that is much better but it does have some limitations: only 12 textures of size 1024x1024. Its specific for rpgmaker

**Comment by ivanpopelyshev** [comment]
Don't worry, I'll rewrite it with types soon.

**Comment by ivanpopelyshev** [comment]
https://github.com/pixijs/pixi-tilemap/tree/dev-multitexture/bin - this one is WIP, use it with pixi-v4.2.2

**Comment by ivanpopelyshev** [comment]
Oh, I forgot to say that pixi-tilemap is on TS already. You dont need typings anymore.
