### ISSUE TITLE
Unable to override UpdateTransform as many variables are private, not protected

### ISSUE THREAD

**Issue by emilekberg** [pixijs/pixi-typescript#9]
I was going to override the updateTransform method in DisplayObject, but many variables were being marked as unfound, as they are marked as private, not protected. 

The ones being marked as error were:
rotationCache
_sr
_cr
_currentBounds

Shouldn't most, or at least some member variables be marked as protected? Or are this a special case where it would be better to make new variables to replace them?

What i was doing was adding skewX and skewY functionality.

**Comment by clark-stevenson** [comment]
Hey @doskallemaskin 

I think you may be right, I cannot see a good reason why they are private in that context. On the day I did a first pass, my goal was to capture the internal functions as to prevent people overriding native functions which is a black hole.  I had overlooked the fact that extending them should always provide access and in fact I cannot think of a reason why that is not possible (and cannot see a need to ever have private members or functions in a definition file). 

On it now.

**Comment by emilekberg** [comment]
Yeah i get that. Some of the variables might be best to keep private though that would be best for the pixi devs to specify i guess, since they would know what's intended to be able to modify and such.  Great job keeping thtis updated, much appreciated!
