### ISSUE TITLE
TilingSprite `From`

### ISSUE THREAD

**Issue by clark-stevenson** [pixijs/pixi-typescript#96]
`TilingSprite` extends `Sprite`.  Both have a static `from`. 

I have no idea how to handle this yet, so taking a note: 

https://github.com/pixijs/pixi-typescript/blob/v4.x/pixi.js.d.ts#L1396

**Comment by andrewstart** [comment]
In theory, static properties and methods should be attached to the class, and not carry over to subclasses, so each class would need to define and implement their own statics.

**Comment by webbiesdk** [comment]
> In theory, static properties and methods should be attached to the class, and not carry over to subclasses, so each class would need to define and implement their own statics.

That is also how most JavaScript libraries (including PIXI) implements classes. But classes in TypeScript inherit static properties, and the types in `pixi.js.d.ts` therefore behaves as such, even though it isn't how the JavaScript implementation works.

**Comment by webbiesdk** [comment]
One way to solve it is to add the following `from` method to TilingSprite: 

```
static from(source: Texture, width?: number, height? :number): Sprite;
```

By making the `width` and `number` attributes optional, the override is valid. 
And the `width` and `height` attributes are actually optional, even though they aren't documented as being so in the JSDoc. 

But shouldn't both `from` methods have the type `number|string|PIXI.BaseTexture|HTMLCanvasElement|HTMLVideoElement` as the first argument?

**Comment by clark-stevenson** [comment]
You were right Webbie, `From` is no longer a problem

However,  `TilingSprite.fromImage` is a pain in the ass.

```
static fromImage(imageId: string, crossorigin?: boolean, scaleMode?: number): Sprite;
static fromImage(imageId: string, width?: number, height?: number, crossorigin?: boolean, scaleMode?: number): TilingSprite;
```

I ended up adding what you suggested for From above. 

Do you know why TypeScript does this? Is this valid ES2015+ ?  Just curious to know who is at fault.

**Comment by webbiesdk** [comment]
TypeScript does their best to be ES2015+ compatible, and classes inheriting static fields is a thing in ES2015+. ([You can try it out in Babel](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&code=class%20Base%20%7B%0A%20%20constructor%28%29%20%7B%0A%20%20%20%20this.field%20%3D%201%3B%0A%20%20%7D%0A%20%20static%20baseStatic%20%3D%202%3B%0A%7D%0A%0Aclass%20Extended%20extends%20Base%20%7B%0A%20%20constructor%28%29%20%7B%0A%20%20%20%20super%28%29%3B%0A%20%20%20%20this.extendedField%20%3D%203%3B%0A%20%20%7D%0A%20%20static%20extendedStatic%20%3D%204%3B%0A%7D%0A%0Aif%20%28Extended.baseStatic%29%20%7B%0A%20%20alert%28%22Static%20fields%20are%20inherited!%22%29%0A%7D)) 

So TypeScript is not to blame. 

I think it is a bad decision, but the decision has been made, and we must deal with it.

**Comment by clark-stevenson** [comment]
Thanks lads 👍
